name: Deploy to GitHub Pages

on:
  push:
    branches:
      - vardaasen

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
          
      - name: Build and deploy
        run: |
          echo "Building website..."
          mkdir -p out
          cp -r src/* out/
          cd out
          touch .nojekyll

          git init
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          
          if git ls-remote --heads origin gh-pages; then
            git checkout gh-pages
          else
            git checkout --orphan gh-pages
          fi

          git add .
          git commit -m "Deploy to GitHub Pages"
          
          git push --force "https://${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git" master:gh-pages
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
