name: Sync vardaasen with Main

on:
  workflow_run:
    workflows: ["Update Version on Main"]
    types:
      - completed

jobs:
  sync-vardaasen:
    if: github.repository_owner == 'vardaasen'
    runs-on: ubuntu-latest

    steps:
    - name: Sjekk ut repository
      uses: actions/checkout@v3
      with:
        fetch-depth: 0  # Hent hele historikken
        fetch: true     # Hent alle grener

    - name: Sett opp Git-bruker for Actions
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"

    - name: Vis tilgjengelige grener (valgfritt for feilsøking)
      run: git branch -r

    - name: Hent main og slå sammen inn i vardaasen
      run: |
        git fetch origin main
        git checkout vardaasen
        git merge origin/main  # Slå sammen endringer fra main til vardaasen
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push oppdaterte vardaasen tilbake til GitHub
      run: |
        git push origin vardaasen
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
