# name: Update Version on Main

# on:
#   push:
#     branches:
#       - main  # Kjøres når det pushes til main

# jobs:
#   update-version:
#     runs-on: ubuntu-latest

#     steps:
#     - name: Sjekk ut repository
#       uses: actions/checkout@v3

#     - name: Hent dagens dato som versjon
#       id: date
#       run: echo "version=$(date +'%Y.%m.%d.%H%M')" >> $GITHUB_ENV

#     - name: Oppdater version.js
#       run: |
#         mkdir -p src/js/utils
#         sed -i 's/const appVersion = .*/const appVersion = "'"$VERSION"'";/' src/js/utils/version.js
#       env:
#         VERSION: ${{ env.version }}

#     - name: Vis innholdet i version.js etter sed
#       run: cat src/js/utils/version.js

#     - name: Sjekk git status før commit
#       run: git status

#     - name: Commit og push oppdatert versjon til main
#       run: |
#         git config --global user.name "GitHub Actions"
#         git config --global user.email "actions@github.com"
#         git add src/js/utils/version.js
#         git commit -m "Update version to $VERSION"
#         git push origin main
#       env:
#         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
