name: Update Version

on:
  push:
    branches:
      - main # kjøres når det pushes til main

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Sjekk ut repository
      uses: actions/checkout@v2

    - name: Hent dagens dato som versjon
      id: date
      run: echo "::set-output name=version::$(date +'%Y.%m.%d.%H%M')"

    - name: Oppdater versjon.js
      run: |
        sed -i 's/const appVersion = .*/const appVersion = "'"${{ steps.date.outputs.version }}"'";/' src/version.js

    - name: Commit og push oppdatert versjon
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add src/version.js
        git commit -m "Update version to ${{ steps.date.outputs.version }}"
        git push
