name: Update Version

on:
  push:
    branches:
      - main # kjøres når det pushes til main

jobs:
  update-version:
    runs-on: ubuntu-latest

    steps:
    - name: Sjekk ut repository
      uses: actions/checkout@v3

    - name: Hent dagens dato som versjon
      id: date
      run: echo "version=$(date +'%Y.%m.%d.%H%M')" >> $GITHUB_ENV

    - name: Oppdater versjon.js
      run: |
        sed -i 's/const appVersion = .*/const appVersion = "'"$VERSION"'";/' src/version.js
      env:
        VERSION: ${{ env.version }}

    - name: Vis innholdet i version.js etter sed
      run: cat src/version.js

    - name: Sjekk git status før commit
      run: git status

    - name: Commit og push oppdatert versjon
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add src/version.js
        git commit -m "Update version to ${{ env.version }}"
        git push
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Hent main og slå sammen inn i feature-grenen
      if: github.repository == 'vardaasen/Nettside-kafe'
      run: |
        git fetch origin main
        git checkout vardaasen
        git merge origin/main
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Push oppdaterte vardaasen-gren til GitHub
      if: github.repository == 'vardaasen/Nettside-kafe'
      run: |
        git push origin vardaasen
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      
